# Generated by Django 4.2.4 on 2023-12-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mood',
            new_name='moods',
        ),
    ]
